### ISSUE TITLE
no attributes available for sensor

### ISSUE THREAD

**Issue by screenagerbe** [eifinger/open_route_service#142]
## Version of the custom_component

1.1.1

## Configuration

```yaml
sensor:
  - platform: open_route_service
    api_key: "MY_API_KEY"
    name: "Pendeltijd"
    origin_entity_id: "zone.home"
    destination_entity_id: "zone.work"
    mode: "driving-car"
```

## Describe the bug
I don't see any useful attributes, except the driving time:
![image](https://user-images.githubusercontent.com/82099983/167489655-81037561-d819-49b8-a957-9ed44a0b5702.png)

Not sure at all, but is this related to missing info in sensor.py (lines 298-327) ?
```python
class OpenRouteTravelTimeData:
    """OpenRouteTravelTimeData data object."""

    def __init__(
        self,
        origin: None,
        destination: None,
        api_key: str,
        travel_mode: str,
        route_mode: str,
        units: str,
        origin_reverse_geocode_enabled: bool,
        destination_reverse_geocode_enabled: bool,
    ) -> None:
        """Initialize openrouteservice."""
        self.origin = origin
        self.destination = destination
        self.travel_mode = travel_mode
        self.route_mode = route_mode
        self.attribution = None
        self.duration = None
        self.distance = None
        self.route = None
        self.base_time = None
        self.origin_name = None
        self.destination_name = None
        self.units = units
        self.origin_reverse_geocode_enabled = origin_reverse_geocode_enabled
        self.destination_reverse_geocode_enabled = destination_reverse_geocode_enabled
        self._client = openrouteservice.Client(key=api_key)

```

## Debug log

No errors or anything else in the logs for this custom component
