### ISSUE TITLE
origin_entity_id  with  home assistant app **_geocoded_location not working

### ISSUE THREAD

**Issue by phiwa99** [eifinger/open_route_service#226]
## Version of the custom_component

newest

## Configuration

```yaml

  - platform: open_route_service
    api_key: "xxxx" # GitHub
    name: Philipp zur Arbeit
    #origin_entity_id: device_tracker.google_maps_1xxxx
   #origin_entity_id: {{state_attr('sensor.pixel_6_geocoded_location','location')}}
    origin_entity_id: sensor.pixel_6_geocoded_location
    destination_entity_id: zone.arbeit_philipp_2
    scan_interval: 5400 # 90min
    #route_mode: fastest

```

## Describe the bug
using the custom component with the _geocoded_location sensor of the home assistant android app is not working
![image](https://user-images.githubusercontent.com/35165536/202675207-be819d49-3644-4e0f-8813-8cbc29694fd3.png)

with the **device_tracker**.google_maps_XXX_gmail_com the sensor works properly
![image](https://user-images.githubusercontent.com/35165536/202677568-a1838d9d-dabe-4fe7-97a0-9b01b40c1105.png)

## Debug log

-->

2022-11-18 09:47:52.185 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.zeit_philipp_XXXX fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 527, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 722, in async_device_update
    raise exc
  File "/config/custom_components/open_route_service/sensor.py", line 295, in async_update
    await self._hass.async_add_executor_job(self._open_route_data.update)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/open_route_service/sensor.py", line 376, in update
    directions_response = self._client.directions(
  File "/usr/local/lib/python3.10/site-packages/openrouteservice/client.py", line 299, in wrapper
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/openrouteservice/directions.py", line 281, in directions
    return client.request("/v2/directions/" + profile + '/' + format, {}, post_json=params, dry_run=dry_run)
  File "/usr/local/lib/python3.10/site-packages/openrouteservice/client.py", line 204, in request
    result = self._get_body(response)
  File "/usr/local/lib/python3.10/site-packages/openrouteservice/client.py", line 242, in _get_body
    raise exceptions.ApiError(
openrouteservice.exceptions.ApiError: 400 ({'error': {'code': 2002, 'message': "Parameter 'Deutschland' has incorrect value or format."}, 'info': {'engine': {'version': '6.8.0', 'build_date': '2022-10-21T14:34:31Z'}, 'timestamp': 1668761271920}})

```
