### ISSUE TITLE
Unable to find entity

### ISSUE THREAD

**Issue by StillLoading** [eifinger/open_route_service#3]
Been using this component for a while now but didn't have the time to integrate it into my notifications. And I just noticed that it does not update anymore. Some troubleshooting revealed that when using entitys instead of long and lat it is unable to find those.

## System
arch | x86_64
-- | --
dev | false
docker | true
hassio | true
os_name | Linux
os_version | 5.6.10-arch1-1
python_version | 3.7.7
timezone | Europe/Berlin
version | 0.109.6
virtualenv | false

## Version of the custom_component
 v1.0.1
## Configuration
```yaml
  - platform: open_route_service
    name: Home To Work
    scan_interval: 900
    api_key: !secret ors_api
    origin_entity_id: zone.home
    destination_entity_id: zone.work
```

```yaml
Logger: custom_components.open_route_service.sensor
Source: custom_components/open_route_service/sensor.py:231
Integration: open_route_service (documentation)
First occurred: 1:37:17 PM (1 occurrences)
Last logged: 1:37:17 PM
Unable to find entity zone.home
```

## Describe the bug
Using entity's to calculate travel time does not work anymore.

**Comment by eifinger** [comment]
That error message means that the entity does not exist according to HA. But as far as I know `zone.home` always exists.

Could you try if it works if you put the entity_id in quotation marks?

**Comment by eifinger** [comment]
Okay zone.home is only created automatically when no other times are defined: https://www.home-assistant.io/integrations/zone/

Can you also show your zone configuration?

**Comment by StillLoading** [comment]
Sorry for the late response.
This is not limited to zones, device trackers don't work either. The zone exists and I can pull it's state from the development tools page.

## zone.home
```yaml
hidden: true
latitude: -removed-
longitude: -removed-
radius: 100
passive: false
editable: true
friendly_name: Home
icon: 'mdi:home'
```

Same error with device tracker.
```text
 Log Details (ERROR)

Logger: custom_components.open_route_service.sensor
Source: custom_components/open_route_service/sensor.py:231
Integration: open_route_service (documentation)
First occurred: 2:37:47 PM (1 occurrences)
Last logged: 2:37:47 PM 

Unable to find entity device_tracker.mi_note_10_pro
```
